version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules # 使用容器内的node_modules，避免与主机冲突
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=carbon_emission_dev
      - JWT_SECRET=dev_secret_key
      - JWT_EXPIRES_IN=30d
    command: npm run start:dev

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carbon_emission_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
