version: '3.8'

services:
  # PostgreSQL 数据库服务
  postgres:
    image: postgres:14
    container_name: carbon-emission-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carbon_emission
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carbon-network
    restart: unless-stopped

  # pgAdmin 管理工具 (可选)
  pgadmin:
    image: dpage/pgadmin4
    container_name: carbon-emission-pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - carbon-network
    restart: unless-stopped

networks:
  carbon-network:
    driver: bridge

volumes:
  postgres_data:
